import BilingualLegal from '@/components/BilingualLegal';

// Server Component. BilingualLegal がクライアント側でトグルUIを提供し、
// 本文は両言語とも SSR で DOM に書き出されるため、SEO・App Storeクローラ両方で検出可能。
export default function EpochCameraTermsPage() {
  return (
    <BilingualLegal
      titleEn="Epoch Camera Terms of Use"
      titleJa="Epoch Camera 利用規約"
      en={<EnglishContent />}
      ja={<JapaneseContent />}
      defaultLang="ja"
    />
  );
}

function EnglishContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>Last Updated:</strong> April 23, 2026 &nbsp;|&nbsp;
        <strong>Effective Date:</strong> April 23, 2026
      </p>
      <p>
        These Terms of Use (&ldquo;Terms&rdquo;) govern your use of the iOS application &ldquo;Epoch Camera&rdquo; (the &ldquo;App&rdquo;) provided by slime design (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;). By installing, downloading, or using the App, you agree to be bound by these Terms. If you do not agree to these Terms, please uninstall the App immediately.
      </p>

      <div>
        <h3 className="font-semibold mb-1">1. Definitions</h3>
        <p>In these Terms, the following terms shall have the meanings set forth below:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>&ldquo;Service&rdquo;</strong> — all features, content, and related services provided through the App.</li>
          <li><strong>&ldquo;User&rdquo;</strong> — any individual or entity that installs the App or uses the Service.</li>
          <li><strong>&ldquo;Content&rdquo;</strong> — any images, videos, text, or other information photographed, edited, or generated by the User through the App.</li>
          <li><strong>&ldquo;AI Features&rdquo;</strong> — features that utilize third-party artificial intelligence models, including Erase Objects, Replace Background, and Style Transfer.</li>
          <li><strong>&ldquo;Third-Party Services&rdquo;</strong> — external services used by us to provide the Service, including Clipdrop (Stability AI), fal.ai, Firebase (Google LLC), RevenueCat, and Apple Inc.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">2. Acceptance of Terms</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>By installing and using the App, you are deemed to have agreed to these Terms.</li>
          <li>If you do not agree to these Terms, you must uninstall the App immediately.</li>
          <li>If you are a minor, you may only use the App with the consent of a parent or legal guardian.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">3. Account</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>The App uses Firebase Anonymous Authentication. No email address or password registration is required.</li>
          <li>An anonymous identifier is automatically generated for each device upon first launch.</li>
          <li>Subscription transfer to a new device is handled via Apple&rsquo;s Restore Purchases feature, which is tied to your Apple ID.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">4. User Obligations and Prohibited Conduct</h3>
        <p>You agree not to engage in any of the following activities while using the Service:</p>
        <ol className="list-[lower-alpha] pl-5 space-y-1 mt-1">
          <li>Upload, edit, or generate images that infringe on the portrait rights, privacy rights, copyrights, or any other rights of third parties.</li>
          <li>Use AI-generated images for malicious purposes including impersonation, defamation, fraud, deepfakes, or harassment.</li>
          <li>Edit images of minors into sexual content, or use the Service for the purpose of sexual exploitation.</li>
          <li>Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code of the App or any Third-Party Service.</li>
          <li>Access the Service through automated scripts, bots, scraping tools, or any other unauthorized means.</li>
          <li>Interfere with the operation of the Service, overload our servers, or engage in any form of attack against our infrastructure.</li>
          <li>Engage in any activity that violates applicable law or public morals.</li>
          <li>Engage in any other activity that we deem inappropriate.</li>
        </ol>
        <p className="mt-1">If you engage in any prohibited conduct, we may suspend your access to the Service without prior notice.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">5. User-Generated Content</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li><strong>Copyright in Content created by you through the App belongs to you.</strong></li>
          <li>We reserve the right to temporarily process your Content to the extent necessary to provide the Service (including AI processing, transmission to Third-Party Services, and return of processed results).</li>
          <li>When your Content is transmitted to Third-Party Services, such Content is <strong>automatically deleted from those services within 24 hours</strong> (per lifecycle management we configure with each service).</li>
          <li>You are solely responsible for the commercial use, social media posting, or distribution to third parties of images generated through AI Features.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">6. AI Features Disclaimer</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>AI Features utilize artificial intelligence models provided by Clipdrop (Stability AI) and fal.ai (using the FLUX.1 Kontext model).</li>
          <li>We make no warranty regarding the accuracy, quality, consistency, or fitness for any particular purpose of the output from AI Features.</li>
          <li>Due to the nature of AI models, different results may be produced for the same input image on each use.</li>
          <li>AI output may contain unintended elements (misrecognized text, distorted shapes, inappropriate depictions, etc.).</li>
          <li>Dissatisfaction with AI output shall not be grounds for refund.</li>
          <li>You are solely responsible for the use, publication, and commercial exploitation of images generated through AI Features.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">7. Subscription and Payment</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>Paid plans (Light, Standard, Pro) are offered as <strong>auto-renewing subscriptions</strong> via Apple In-App Purchase.</li>
          <li>Payment is charged to your Apple ID at confirmation of purchase.</li>
          <li>Subscriptions automatically renew unless <strong>auto-renewal is turned off at least 24 hours before</strong> the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period.</li>
          <li>No free trial is offered. However, new users may try AI Features 3 times at no cost.</li>
          <li>
            Subscription management, cancellation, and plan changes are performed via your iPhone&rsquo;s Settings app:
            <br />
            <span className="text-gray-600">Settings → [Your Name (Apple ID)] → Subscriptions → Epoch Camera → Cancel Subscription / Change Plan</span>
          </li>
          <li>Refunds must be requested directly from Apple in accordance with Apple&rsquo;s refund policy. We cannot process refunds directly.</li>
          <li>Plan changes take effect at your next renewal date.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">8. Intellectual Property</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>All intellectual property rights in the App, including filters, UI, logos, source code, text, images, and other assets, belong to us or our licensors.</li>
          <li>These Terms do not grant you any license to the App&rsquo;s intellectual property.</li>
          <li>Content provided by Third-Party Services (fonts, models, libraries, etc.) belongs to their respective owners and is governed by their respective terms and licenses.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">9. Third-Party Services</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>
            The Service uses the following Third-Party Services. By using the Service, you agree to also be bound by their respective terms of service and privacy policies:
            <ul className="list-disc pl-5 mt-1 space-y-0.5">
              <li>Apple Inc. (iOS, App Store, In-App Purchase)</li>
              <li>Google LLC (Firebase, Firebase Cloud Functions, Firestore, Firebase Authentication, Firebase App Check)</li>
              <li>Stability AI Ltd. (Clipdrop API)</li>
              <li>fal.ai (FLUX.1 Kontext model)</li>
              <li>RevenueCat, Inc. (subscription management)</li>
            </ul>
          </li>
          <li>Changes to, or discontinuation of, Third-Party Services may affect the availability of certain features. We are not liable for any damages arising from such changes.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">10. Disclaimer and Limitation of Liability</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>The Service is provided &ldquo;as-is&rdquo; and &ldquo;as-available&rdquo;.</li>
          <li>We disclaim all warranties, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, non-infringement, absence of viruses, and uninterrupted availability.</li>
          <li>Except in cases of our willful misconduct or gross negligence, our total liability to you shall not exceed the lesser of: (a) the total subscription fees paid by you to us in the 12 months immediately preceding the event giving rise to the claim, or (b) one thousand Japanese yen (¥1,000).</li>
          <li>We shall not be liable for any indirect, special, incidental, consequential, or punitive damages, including loss of profits, loss of data, or business interruption.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">11. Consumer Rights (GDPR — EU/UK Residents)</h3>
        <p>If you are a resident of the European Union or the United Kingdom, you have the following rights regarding your personal data:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li><strong>Right of access</strong> to your personal data</li>
          <li><strong>Right to rectification</strong> of inaccurate data</li>
          <li><strong>Right to erasure</strong> (&ldquo;right to be forgotten&rdquo;)</li>
          <li><strong>Right to data portability</strong></li>
          <li><strong>Right to restrict processing</strong></li>
          <li><strong>Right to object</strong> to processing</li>
        </ul>
        <p className="mt-1">To exercise these rights, contact us at <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a>. We will respond within 30 days.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">12. Consumer Rights (CCPA — California Residents)</h3>
        <p>If you are a California resident, you have the following rights under the California Consumer Privacy Act:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li><strong>Right to know</strong> what personal information we collect and how we use it</li>
          <li><strong>Right to delete</strong> your personal information</li>
          <li><strong>Right to opt-out</strong> of the sale of personal information (note: we do not sell personal information)</li>
          <li><strong>Right to non-discrimination</strong> for exercising your rights</li>
        </ul>
        <p className="mt-1">To exercise these rights, contact us at <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a>.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">13. International Data Transfer</h3>
        <p>The Service is operated from Japan, but data may be processed in the United States and other countries where Third-Party Services operate. By using the Service, you consent to the transfer of your data to these countries, which may have different data protection standards than your home country.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">14. DMCA Notice</h3>
        <p>If you believe content in the App infringes your copyright, please send a notice to <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a> with the following information:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>A description of the copyrighted work you claim is infringed</li>
          <li>The location of the infringing material in the App</li>
          <li>Your contact information</li>
          <li>A statement under penalty of perjury that the information is accurate and you are authorized to act on behalf of the copyright owner</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">15. Service Modifications and Termination</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>We may modify, add to, or discontinue the Service at any time without prior notice.</li>
          <li>For significant changes or discontinuation of the Service, we will use reasonable efforts to provide prior notice via in-app notification or posting on <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a>.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">16. Governing Law and Jurisdiction</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>These Terms shall be governed by and construed in accordance with the laws of Japan.</li>
          <li>Any disputes arising out of or relating to the Service or these Terms shall be subject to the <strong>exclusive jurisdiction of the Tokyo District Court</strong> as the court of first instance.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">17. Changes to These Terms</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>We may revise these Terms from time to time.</li>
          <li>Changes become effective upon posting the revised Terms in the App or at <a href="https://yaneyuka.com/epoch-camera-terms/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/epoch-camera-terms/</a>.</li>
          <li>Your continued use of the Service after the effective date of revised Terms constitutes acceptance of the changes.</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">18. Severability</h3>
        <p>If any provision of these Terms is held to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall remain in full force and effect.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">19. Contact</h3>
        <p>For inquiries regarding these Terms, please contact us at:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>Company:</strong> slime design</li>
          <li><strong>Email:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>Website:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 slime design. All rights reserved.
      </p>
    </div>
  );
}

function JapaneseContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>最終更新日:</strong> 2026年4月23日 &nbsp;|&nbsp;
        <strong>初版制定日:</strong> 2026年4月23日
      </p>
      <p>
        この利用規約（以下「本規約」）は、slime design（以下「当方」）が提供する iOS アプリケーション「Epoch Camera」（以下「本アプリ」）の利用条件を定めるものです。本アプリをインストール、ダウンロード、または利用することにより、お客様は本規約のすべての条項に同意したものとみなされます。
      </p>

      <div>
        <h3 className="font-semibold mb-1">第1条（定義）</h3>
        <p>本規約において使用する用語の意義は次のとおりとします。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>「本サービス」</strong> — 本アプリを通じて当方が提供するすべての機能、コンテンツ、関連サービス</li>
          <li><strong>「利用者」</strong> — 本アプリをインストール、または本サービスを利用するすべての個人または法人</li>
          <li><strong>「コンテンツ」</strong> — 利用者が本アプリで撮影・加工・生成した画像、動画、テキストその他の情報</li>
          <li><strong>「AI機能」</strong> — 被写体除去（Erase Objects）、背景置換（Replace Background）、スタイル変換（Style Transfer）等、第三者の人工知能モデルを利用する機能</li>
          <li><strong>「第三者サービス」</strong> — Clipdrop (Stability AI社)、fal.ai、Firebase (Google LLC)、RevenueCat、Apple Inc. 等、本サービスの提供にあたり当方が利用する外部サービス</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第2条（本規約への同意）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>利用者は、本アプリのインストールおよび利用をもって、本規約に同意したものとみなされます。</li>
          <li>本規約に同意いただけない場合は、本アプリを直ちにアンインストールしてください。</li>
          <li>利用者が未成年者である場合は、親権者その他の法定代理人の同意を得た上で本アプリを利用するものとします。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第3条（アカウント）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>本アプリは、Firebase Anonymous Auth による匿名認証を採用しており、メールアドレスやパスワードによるアカウント登録は不要です。</li>
          <li>本アプリの初回起動時に、デバイスごとに匿名識別子が自動生成されます。</li>
          <li>機種変更時のサブスクリプション引き継ぎは、Apple ID に紐づく購入履歴の復元機能（Restore Purchases）により行います。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第4条（利用者の義務および禁止事項）</h3>
        <p>利用者は、本サービスの利用にあたり、以下の行為を行ってはなりません。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>第三者の肖像権、プライバシー権、著作権その他の権利を侵害する画像をアップロード、加工、または生成する行為</li>
          <li>AI機能を利用して生成した画像を、なりすまし、名誉毀損、詐欺、Deepfake、その他悪意ある目的に使用する行為</li>
          <li>未成年者の画像を性的な表現に加工する行為、または性的搾取を目的とする行為</li>
          <li>本アプリまたは第三者サービスに対するリバースエンジニアリング、逆コンパイル、逆アセンブル、その他ソースコード解析行為</li>
          <li>自動化スクリプト、ボット、スクレイピングツールその他の手段により本サービスに不正にアクセスする行為</li>
          <li>本サービスの運営を妨害する行為、サーバーに過度の負荷を与える行為、攻撃行為</li>
          <li>法令または公序良俗に反する行為</li>
          <li>その他、当方が不適切と判断する行為</li>
        </ol>
        <p className="mt-1">利用者が前項各号のいずれかに該当する行為を行った場合、当方は利用者に対する本サービスの提供を予告なく停止することができるものとします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第5条（利用者が作成したコンテンツの取扱い）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>利用者が本アプリで撮影、加工、または生成したコンテンツの<strong>著作権は、利用者に帰属</strong>します。</li>
          <li>当方は、本サービスの提供（AI処理、第三者サービスへの送信、処理結果の返却など）のために必要な限度において、利用者のコンテンツを一時的に処理する権利を有します。</li>
          <li>利用者のコンテンツが第三者サービスに送信される場合、当該コンテンツは<strong>24時間以内に各サービスから自動的に削除</strong>されます（当方が各サービスに設定するライフサイクル管理による）。</li>
          <li>AI機能により生成された画像の商用利用、SNS投稿、第三者への提供は、利用者の判断と責任において行うものとします。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第6条（AI機能に関する留意事項）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>AI機能は、Clipdrop (Stability AI 社) および fal.ai（FLUX.1 Kontext モデル使用）の提供する人工知能モデルを利用しています。</li>
          <li>当方は、AI機能の出力結果の正確性、品質、一貫性、および特定の目的への適合性について、いかなる保証も行いません。</li>
          <li>同一の入力画像に対しても、AIモデルの特性上、毎回異なる出力結果が得られる場合があります。</li>
          <li>AI出力物に意図しない要素（文字の誤認識、形状の歪み、不適切な描写等）が含まれる可能性があります。</li>
          <li>生成結果が利用者の期待と異なることを理由とする返金請求の対象にはなりません。</li>
          <li>AI機能により生成された画像の使用、公開、商業利用に関するすべての責任は、利用者が負うものとします。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第7条（サブスクリプションおよび支払い）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>本アプリの有料プラン（Light、Standard、Pro）は、Apple In-App Purchase を通じて提供される<strong>自動更新サブスクリプション</strong>です。</li>
          <li>料金は、Apple ID に登録されたお支払い方法により、購入確定時に請求されます。</li>
          <li>サブスクリプションは、現在の契約期間終了日の<strong>24時間以上前に自動更新をオフ</strong>にしない限り、自動的に更新されます。更新料金は、現在の契約期間終了日前の24時間以内に請求されます。</li>
          <li>無料トライアル期間は提供していません(ただし新規利用者には初回のお試しとして AI機能を合計3回無料で試用可能です)。</li>
          <li>
            サブスクリプションの管理、キャンセル、プラン変更は、iPhone の「設定」アプリから以下の手順で行います:
            <br />
            <span className="text-gray-600">「設定」→「ユーザー名(Apple ID)」→「サブスクリプション」→「Epoch Camera」→「キャンセル」または「プラン変更」</span>
          </li>
          <li>返金は Apple の返金ポリシーに従い、Apple に対して直接リクエストしていただく必要があります。当方は返金処理を行うことができません。</li>
          <li>プラン変更は Apple ID のサブスクリプション設定から行い、次回更新時から適用されます。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第8条（知的財産権）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>本アプリ、本アプリに含まれるフィルター、ユーザーインターフェース、ロゴ、ソースコード、文字列、画像、動画その他のアセットに関する著作権、商標権、特許権その他一切の知的財産権は、当方または正当なライセンスを有する第三者に帰属します。</li>
          <li>本規約は、利用者に対し本アプリに関するいかなる知的財産権のライセンス許諾も行うものではありません。</li>
          <li>第三者サービスの提供するコンテンツ、フォント、モデル、ライブラリ等の著作権は、各提供元に帰属し、各サービスの利用規約およびライセンス条件に従います。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第9条（第三者サービス）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>
            本サービスは、以下の第三者サービスを利用しています。利用者は、本サービスの利用にあたり、各サービスの利用規約およびプライバシーポリシーにも同時に拘束されることに同意します。
            <ul className="list-disc pl-5 mt-1 space-y-0.5">
              <li>Apple Inc.（iOS、App Store、In-App Purchase）</li>
              <li>Google LLC（Firebase、Firebase Cloud Functions、Firestore、Firebase Authentication、Firebase App Check）</li>
              <li>Stability AI Ltd.（Clipdrop API）</li>
              <li>fal.ai（FLUX.1 Kontext モデル）</li>
              <li>RevenueCat, Inc.（サブスクリプション管理）</li>
            </ul>
          </li>
          <li>第三者サービスの仕様変更、提供終了、障害等により、本サービスの一部機能が利用できなくなる場合があります。当方はこれらに起因する損害について責任を負いません。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第10条（保証の否認および責任の制限）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>本サービスは、「現状有姿（as-is）」「現状可能（as-available）」の状態で提供されます。</li>
          <li>当方は、本サービスについて、明示または黙示を問わず、商品性、特定目的への適合性、第三者の権利の非侵害、ウイルスその他の有害物質の不存在、中断のない継続的な提供その他一切の保証を行いません。</li>
          <li>当方が利用者に対して負う損害賠償責任の総額は、当方に故意または重過失がある場合を除き、利用者が損害発生直前の12か月間に当方に支払ったサブスクリプション料金の総額、または金1,000円のいずれか少ない金額を上限とします。</li>
          <li>当方は、間接損害、特別損害、付随的損害、結果的損害、逸失利益、データの喪失、事業の中断等の損害について、一切の責任を負いません。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第11条（サービスの変更・終了）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>当方は、利用者への事前の予告なく、本サービスの内容を変更、追加、または終了することができます。</li>
          <li>本サービスの重大な変更または終了を行う場合、当方は合理的な範囲で、アプリ内通知または <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a> 上での告知により、事前の通知を試みます。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第12条（準拠法および管轄裁判所）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>本規約の解釈および適用は、日本法に準拠します。</li>
          <li>本サービスまたは本規約に関連して利用者と当方との間で紛争が生じた場合、<strong>東京地方裁判所</strong>を第一審の専属的合意管轄裁判所とします。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第13条（規約の変更）</h3>
        <ol className="list-decimal pl-5 space-y-1">
          <li>当方は、必要に応じて本規約を変更することができます。</li>
          <li>本規約の変更は、変更後の規約をアプリ内に表示するか、または <a href="https://yaneyuka.com/epoch-camera-terms/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/epoch-camera-terms/</a> 上に掲載することにより効力を生じます。</li>
          <li>変更後の規約の発効日以降も利用者が本サービスの利用を継続した場合、利用者は変更後の規約に同意したものとみなされます。</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第14条（分離可能性）</h3>
        <p>本規約のいずれかの条項が裁判所により無効または執行不能と判断された場合であっても、本規約の他の条項の有効性および執行可能性には影響を及ぼさないものとします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">第15条（お問い合わせ）</h3>
        <p>本規約に関するお問い合わせは、以下の連絡先までお願いいたします。</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>事業者:</strong> slime design</li>
          <li><strong>メール:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>ウェブサイト:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 slime design. All rights reserved.
      </p>
    </div>
  );
}
