import BilingualLegal from '@/components/BilingualLegal';

// Server Component. BilingualLegal がクライアント側でトグルUIを提供し、
// 本文は両言語とも SSR で DOM に書き出されるため、SEO・App Storeクローラ両方で検出可能。
export default function FxSignalPrivacyPolicyPage() {
  return (
    <BilingualLegal
      titleEn="FX Signal Privacy Policy"
      titleJa="FX Signal プライバシーポリシー"
      en={<EnglishContent />}
      ja={<JapaneseContent />}
      defaultLang="ja"
    />
  );
}

function EnglishContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>Last Updated:</strong> May 10, 2026 &nbsp;|&nbsp;
        <strong>Effective Date:</strong> May 10, 2026
      </p>
      <p>
        slime design, LLC (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) respects your privacy and is committed to protecting your personal information in connection with your use of the iOS application &ldquo;FX Signal&rdquo; (the &ldquo;App&rdquo;). This Privacy Policy (&ldquo;Policy&rdquo;) describes the categories of data we handle, how we collect them, the purposes of use, third parties to whom data is disclosed, retention periods, and your rights regarding your data.
      </p>

      <div>
        <h3 className="font-semibold mb-1">1. Who We Are</h3>
        <ul className="list-disc pl-5 space-y-0.5">
          <li><strong>Controller:</strong> slime design, LLC (合同会社slime)</li>
          <li><strong>Contact:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>Website:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">2. Information We Collect</h3>
        <p>We collect only the minimum information necessary to provide the Service.</p>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-1. Information Collected Automatically</h4>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Anonymous Identifier:</strong> A unique anonymous UID generated by Firebase Anonymous Authentication for each device.</li>
          <li><strong>Push Notification Token:</strong> A Firebase Cloud Messaging (FCM) registration token issued by Apple Push Notification Service (APNs), used solely to deliver signal alerts.</li>
          <li><strong>Subscription Data:</strong> Subscription status and purchase history tied to your Apple ID, managed through RevenueCat.</li>
          <li><strong>App Usage Counts:</strong> Counts associated with free-plan limits (number of watched pairs, signals, and timeframes) used to enforce plan quotas.</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-2. Information You Configure</h4>
        <p>The following information is stored in our Firestore database so that our backend can monitor your selected signals on your behalf 24/7:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li><strong>Watched Currency Pairs:</strong> Up to 25 pairs you choose to monitor (e.g., USD/JPY, EUR/USD)</li>
          <li><strong>Watched Timeframes:</strong> Which of the 7 timeframes (5min, 10min, 30min, 1H, 4H, daily, weekly) you want monitored</li>
          <li><strong>Signal Configuration:</strong> RSI thresholds, SMA cross types, disparity thresholds, breakout settings, round-number levels, sudden-change thresholds</li>
          <li><strong>Notification Preferences:</strong> Quiet hours, mute settings, etc.</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-3. Information We Do NOT Collect</h4>
        <p>We expressly do <strong>not</strong> collect the following:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Name, address, phone number, or email address (or any personally identifiable information). The only exception is if you voluntarily contact us via email — in which case we receive only what you write in that email.</li>
          <li>Location data (GPS)</li>
          <li>Advertising Identifier (IDFA)</li>
          <li>Contacts, calendar, photos, or other personal data</li>
          <li>Biometric data</li>
          <li>Brokerage account credentials, account balances, or any trading account information. The App does <strong>not</strong> connect to your brokerage account.</li>
          <li>Behavioral analytics or tracking data (at initial release)</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">3. Source of Market Data</h3>
        <p>Currency price data used to detect signals is fetched <strong>by our backend</strong> from public market-data sources (e.g., OANDA, MT5 data feeds). Market data is anonymous price-tick data that is not associated with your account. Your device does not connect directly to any brokerage.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">4. How We Use Your Information</h3>
        <p>We use collected information solely for the following purposes:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>To monitor currency pairs and timeframes you configured</li>
          <li>To deliver push notifications when configured signals fire</li>
          <li>To manage subscriptions and billing</li>
          <li>To enforce plan-tier limits on watched pairs, signal types, and timeframes</li>
          <li>To detect and prevent abuse, service interference, and attacks</li>
          <li>To comply with applicable laws</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">5. Sharing of Information</h3>
        <p>We do not share your information with third parties except in the following cases:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>When required by law</li>
          <li>When necessary to protect life, safety, or property</li>
          <li>With sub-processors as described in Section 6</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">6. Sub-Processors</h3>
        <p>The App uses the following third-party services. Your information may be processed by these sub-processors on our behalf:</p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">Provider</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Service</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Data Handled</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Retention</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Apple Inc. (USA)</td>
                <td className="border border-gray-300 px-2 py-1">iOS, App Store, In-App Purchase, APNs</td>
                <td className="border border-gray-300 px-2 py-1">Apple ID, purchase data, push notification routing</td>
                <td className="border border-gray-300 px-2 py-1">Per Apple policy</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Google LLC (USA)</td>
                <td className="border border-gray-300 px-2 py-1">Firebase Authentication / Firestore / Cloud Functions / Cloud Messaging (FCM) / App Check</td>
                <td className="border border-gray-300 px-2 py-1">Anonymous UID, FCM token, signal configuration, notification logs</td>
                <td className="border border-gray-300 px-2 py-1">Until account deletion / uninstall</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">RevenueCat, Inc. (USA)</td>
                <td className="border border-gray-300 px-2 py-1">Subscription management</td>
                <td className="border border-gray-300 px-2 py-1">Anonymous UID, purchase data</td>
                <td className="border border-gray-300 px-2 py-1">Per RevenueCat policy</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-2">Each sub-processor maintains its own privacy policy, and data is handled in accordance with those policies. The privacy policies of each provider are available below:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Apple Inc.: <a href="https://www.apple.com/legal/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.apple.com/legal/privacy/</a></li>
          <li>Google LLC: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a></li>
          <li>RevenueCat, Inc.: <a href="https://www.revenuecat.com/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.revenuecat.com/privacy/</a></li>
        </ul>
        <p className="mt-2">We have entered into Data Processing Agreements (DPAs) with each sub-processor and have confirmed that they provide a level of data protection equivalent to or higher than that set forth in this Policy.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">7. International Data Transfer</h3>
        <p>Your data may be transmitted to and stored on servers located outside Japan (primarily in the United States and Europe). The data protection laws of these countries may differ from those of your country of residence. By using the App, you consent to such international transfer.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">8. Data Retention</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Anonymous UID, FCM token, signal configuration, notification logs:</strong> Retained in our Firestore database for the operation of the Service while you continue to use the App. Uninstalling the App stops further data accumulation; existing data is retained for 90 days for billing reconciliation, then deleted.</li>
          <li><strong>Subscription data:</strong> Retained by RevenueCat as purchase history.</li>
          <li><strong>Diagnostic logs (server-side):</strong> Retained for up to 30 days for debugging and abuse prevention.</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">9. Your Rights</h3>
        <p>You have the following rights regarding your information:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>Right of Access</strong> — to request disclosure of your information</li>
          <li><strong>Right to Rectification</strong> — to correct inaccurate information</li>
          <li><strong>Right to Erasure</strong> — to request deletion (note: since the UID is device-dependent, uninstalling the App effectively deletes your anonymous record on next cleanup cycle)</li>
          <li><strong>Right to Object</strong> — to restrict certain processing</li>
        </ol>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">GDPR Rights (EU/UK Residents)</h4>
        <p>In addition to the above, if you are a resident of the European Union or United Kingdom, you have:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Right to data portability</li>
          <li>Right to lodge a complaint with a supervisory authority</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">CCPA Rights (California Residents)</h4>
        <p>If you are a California resident, you have:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Right to know what personal information we collect and how we use it</li>
          <li>Right to delete your personal information</li>
          <li>Right to opt-out of sale (note: <strong>we do not sell personal information</strong>)</li>
          <li>Right to non-discrimination for exercising your rights</li>
        </ul>

        <p className="mt-2">To exercise any of these rights, contact <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a>. We will respond within 30 days.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">10. Cookies and Similar Technologies</h3>
        <p>The App does not use web browser cookies. Firebase and RevenueCat SDKs may store anonymous identifiers in local device storage (UserDefaults / Keychain), but these are not used for tracking purposes.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">11. Children&rsquo;s Privacy</h3>
        <p>The App is not intended for children under the age of 13, and is intended for adults capable of independently making financial decisions. Children under 13 should not use the App. If we discover that we have collected information from a child under 13, we will promptly delete such information.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">12. Security</h3>
        <p>We take the following measures to protect your information from unauthorized access, alteration, and disclosure:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Firebase App Check to prevent unauthorized API access</li>
          <li>HTTPS/TLS encryption for all data transmission</li>
          <li>Server-side subscription verification to prevent client-side tampering</li>
          <li>Data Processing Agreements with all third-party sub-processors</li>
        </ul>
        <p className="mt-1">However, no method of transmission over the internet is 100% secure.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">13. Changes to This Policy</h3>
        <p>We may update this Policy from time to time in response to changes in law, service features, or other circumstances. Updated policies take effect upon posting at <a href="https://yaneyuka.com/fx-signal-privacy-policy/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/fx-signal-privacy-policy/</a>.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">14. Governing Law and Jurisdiction</h3>
        <p>This Policy is governed by the laws of Japan. Any disputes arising from this Policy shall be subject to the exclusive jurisdiction of the Tokyo District Court as the court of first instance.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">15. Contact Us</h3>
        <p>For inquiries regarding this Policy, to request disclosure, or to exercise your rights, please contact:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>Company:</strong> slime design, LLC (合同会社slime)</li>
          <li><strong>Email:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>Website:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 slime design, LLC. All rights reserved.
      </p>
    </div>
  );
}

function JapaneseContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>最終更新日:</strong> 2026年5月10日 &nbsp;|&nbsp;
        <strong>初版制定日:</strong> 2026年5月10日
      </p>
      <p>
        合同会社slime（以下「当社」）は、iOS アプリケーション「FX Signal」（以下「本アプリ」）のご利用にあたり、利用者のプライバシーを尊重し、個人情報の保護に努めます。本プライバシーポリシー（以下「本ポリシー」）は、本アプリにおいて取り扱う情報の種類、収集方法、利用目的、第三者提供先、保管期間、利用者の権利について定めるものです。
      </p>

      <div>
        <h3 className="font-semibold mb-1">1. 事業者情報</h3>
        <ul className="list-disc pl-5 space-y-0.5">
          <li><strong>事業者名:</strong> 合同会社slime</li>
          <li><strong>連絡先:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>ウェブサイト:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">2. 収集する情報</h3>
        <p>本アプリは、以下の情報を必要最小限の範囲で収集・処理します。</p>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-1. 自動的に収集される情報</h4>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>匿名識別子:</strong> Firebase Anonymous Authentication により生成される匿名 UID（端末ごとに一意）</li>
          <li><strong>プッシュ通知トークン:</strong> Apple Push Notification Service（APNs）が発行し Firebase Cloud Messaging（FCM）が管理する登録トークン。シグナル通知を配信する目的にのみ使用します。</li>
          <li><strong>サブスクリプション情報:</strong> Apple ID に紐づくサブスクリプション状態、購入履歴（RevenueCat を通じて管理）</li>
          <li><strong>利用カウント:</strong> 無料プラン上限管理のための、監視対象ペア数 / シグナル数 / 時間足数のカウント</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-2. 利用者が設定する情報</h4>
        <p>当社のバックエンドが24時間体制でシグナル監視を行うため、以下の情報を当社の Firestore データベースに保存します。</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li><strong>監視通貨ペア:</strong> 利用者が選択した最大25ペア（例: USD/JPY、EUR/USD等）</li>
          <li><strong>監視時間足:</strong> 7つの時間足（5分、10分、30分、1時間、4時間、日足、週足）のうち利用者が選択したもの</li>
          <li><strong>シグナル設定値:</strong> RSI 閾値、SMA クロス種別、乖離率閾値、ブレイクアウト設定、キリ番設定、急騰急落閾値等</li>
          <li><strong>通知設定:</strong> サイレント時間帯、ミュート設定等</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-3. 収集しない情報</h4>
        <p>以下の情報は<strong>一切収集いたしません</strong>。</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>実名、住所、電話番号、メールアドレスなどの個人識別情報（ただし利用者がご自身の判断で当社にメールでお問い合わせいただいた場合は、その本文に含まれる情報のみ受領します）</li>
          <li>位置情報（GPS）</li>
          <li>広告識別子（IDFA）</li>
          <li>連絡先、カレンダー、写真などの個人データ</li>
          <li>生体情報</li>
          <li><strong>証券会社／FX 会社のアカウント情報、残高情報、取引履歴等</strong>。本アプリは利用者のブローカー口座に接続しません。</li>
          <li>利用者の行動ログ、アナリティクス（初回リリース時点）</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">3. 相場データの取得元</h3>
        <p>シグナル検出に用いる為替レートデータは、<strong>当社のバックエンドサーバー</strong>が、公開市場データソース（OANDA、MT5 等のマーケットデータフィード）から取得します。市場データは匿名の価格ティックデータであり、利用者のアカウントとは結びつきません。利用者の端末がブローカーに直接接続することはありません。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">4. 利用目的</h3>
        <p>当社は、収集した情報を以下の目的でのみ利用します。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>利用者が設定した通貨ペアと時間足の監視を行うため</li>
          <li>設定されたシグナルが発動した際にプッシュ通知を配信するため</li>
          <li>サブスクリプションおよび課金を管理するため</li>
          <li>プラン階層に応じた監視対象数の上限管理のため</li>
          <li>不正利用、サービス妨害、攻撃行為等への対処</li>
          <li>法令遵守のため</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">5. 第三者への提供</h3>
        <p>当社は、利用者の情報を本人の同意なく第三者に提供することはありません。ただし、以下の場合は例外とします。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>法令に基づく開示請求があった場合</li>
          <li>人の生命、身体または財産の保護のために必要がある場合</li>
          <li>本ポリシー第6条に定めるサブプロセッサーへの提供</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">6. サブプロセッサー</h3>
        <p>本アプリは、以下の第三者サービスを利用します。利用者の情報の一部は、当該サービスの提供事業者に処理委託されます。</p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">事業者</th>
                <th className="border border-gray-300 px-2 py-1 text-left">サービス</th>
                <th className="border border-gray-300 px-2 py-1 text-left">取り扱うデータ</th>
                <th className="border border-gray-300 px-2 py-1 text-left">保存期間</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Apple Inc.（米国）</td>
                <td className="border border-gray-300 px-2 py-1">iOS, App Store, In-App Purchase, APNs</td>
                <td className="border border-gray-300 px-2 py-1">Apple ID, 購入情報, プッシュ通知配信</td>
                <td className="border border-gray-300 px-2 py-1">Apple ポリシーに準拠</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Google LLC（米国）</td>
                <td className="border border-gray-300 px-2 py-1">Firebase Authentication / Firestore / Cloud Functions / Cloud Messaging (FCM) / App Check</td>
                <td className="border border-gray-300 px-2 py-1">匿名UID, FCMトークン, シグナル設定値, 通知履歴</td>
                <td className="border border-gray-300 px-2 py-1">アカウント削除またはアンインストールまで</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">RevenueCat, Inc.（米国）</td>
                <td className="border border-gray-300 px-2 py-1">サブスクリプション管理</td>
                <td className="border border-gray-300 px-2 py-1">匿名UID, 購入情報</td>
                <td className="border border-gray-300 px-2 py-1">RevenueCat ポリシーに準拠</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-2">各サブプロセッサーは、それぞれ独自のプライバシーポリシーを有しており、当該ポリシーに従ってデータを取り扱います。各社のプライバシーポリシーは下記からご確認いただけます。</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Apple Inc.: <a href="https://www.apple.com/legal/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.apple.com/legal/privacy/</a></li>
          <li>Google LLC: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a></li>
          <li>RevenueCat, Inc.: <a href="https://www.revenuecat.com/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.revenuecat.com/privacy/</a></li>
        </ul>
        <p className="mt-2">当社は、各サブプロセッサーとの間で Data Processing Agreement（DPA）を締結し、当社が本ポリシーで提供する水準と同等以上のデータ保護措置が講じられていることを確認しています。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">7. 国際データ移転</h3>
        <p>本アプリを提供するにあたり、利用者のデータは日本国外（主に米国および欧州）のサーバーに送信・保管される場合があります。これらの国の個人情報保護規制は、利用者の居住国と異なる場合があります。本アプリの利用により、利用者は当該国へのデータ移転に同意したものとみなされます。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">8. 保存期間</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>匿名UID、FCMトークン、シグナル設定値、通知履歴:</strong> 本アプリの継続利用中は、サービス提供のため当社が管理する Firestore 内に保存します。本アプリをアンインストールするとデータ蓄積は停止し、課金照合の都合により最大90日間保持した後に削除されます。</li>
          <li><strong>サブスクリプション情報:</strong> RevenueCat 側で購入履歴として保管</li>
          <li><strong>診断ログ（サーバーサイド）:</strong> デバッグおよび不正利用防止のため、最長30日間保管</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">9. ユーザーの権利</h3>
        <p>利用者は、本アプリで処理される自己の情報について、以下の権利を有します。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>アクセス権:</strong> 当社が保有する利用者の情報の開示を求める権利</li>
          <li><strong>訂正権:</strong> 不正確な情報の訂正を求める権利</li>
          <li><strong>削除権:</strong> 情報の削除を求める権利（ただし、匿名UIDはデバイス依存のため、アプリのアンインストールにより次回クリーンアップサイクルで実質的に削除されます）</li>
          <li><strong>処理停止権:</strong> 特定の処理の停止を求める権利</li>
        </ol>
        <p className="mt-1">これらの権利を行使する場合は、<a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a> までご連絡ください。原則として30日以内に対応いたします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">10. Cookie および類似技術</h3>
        <p>本アプリは、Web ブラウザで使用される Cookie を利用しません。Firebase および RevenueCat の SDK が、アプリ内で匿名識別子を UserDefaults / Keychain（端末ローカル）に保存する場合がありますが、これらは追跡目的では使用されません。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">11. 子どもの利用</h3>
        <p>本アプリは13歳未満の児童を対象としていません。また、本アプリは自らの判断で金融的意思決定を行える成人を利用対象として想定しています。13歳未満のお子様は、本アプリを利用しないでください。万一、13歳未満の児童から情報を収集したことが判明した場合、当社は速やかに当該情報を削除いたします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">12. セキュリティ</h3>
        <p>当社は、収集した情報を不正アクセス、改ざん、漏洩から保護するため、以下の措置を講じます。</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Firebase App Check による不正なAPIアクセスの防止</li>
          <li>HTTPS/TLS による通信の暗号化</li>
          <li>サーバーサイドでのサブスクリプション検証（クライアント改変による課金回避の防止）</li>
          <li>第三者サービスとの Data Processing Agreement 締結</li>
        </ul>
        <p className="mt-1">ただし、インターネット経由のデータ送信において100%安全な手段は存在しないことをご承知おきください。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">13. ポリシーの変更</h3>
        <p>当社は、法令の変更、サービス内容の変更その他の事情に応じて、本ポリシーを随時変更することがあります。変更後のポリシーは、<a href="https://yaneyuka.com/fx-signal-privacy-policy/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/fx-signal-privacy-policy/</a> に掲載した時点から効力を生じます。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">14. 準拠法および管轄</h3>
        <p>本ポリシーは日本法に準拠します。本ポリシーに関連する紛争については、東京地方裁判所を第一審の専属的合意管轄裁判所とします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">15. お問い合わせ</h3>
        <p>本ポリシーに関するご質問、情報開示請求、削除請求等は、下記までご連絡ください。</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>事業者:</strong> 合同会社slime</li>
          <li><strong>メール:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>ウェブサイト:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 合同会社slime. All rights reserved.
      </p>
    </div>
  );
}
