import BilingualLegal from '@/components/BilingualLegal';

// Server Component. BilingualLegal がクライアント側でトグルUIを提供し、
// 本文は両言語とも SSR で DOM に書き出されるため、SEO・App Storeクローラ両方で検出可能。
export default function EpochCameraPrivacyPolicyPage() {
  return (
    <BilingualLegal
      titleEn="Epoch Camera Privacy Policy"
      titleJa="Epoch Camera プライバシーポリシー"
      en={<EnglishContent />}
      ja={<JapaneseContent />}
      defaultLang="ja"
    />
  );
}

function EnglishContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>Last Updated:</strong> May 3, 2026 &nbsp;|&nbsp;
        <strong>Effective Date:</strong> April 23, 2026
      </p>
      <p>
        slime design (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) respects your privacy and is committed to protecting your personal information in connection with your use of the iOS application &ldquo;Epoch Camera&rdquo; (the &ldquo;App&rdquo;). This Privacy Policy (&ldquo;Policy&rdquo;) describes the categories of data we handle, how we collect them, the purposes of use, third parties to whom data is disclosed, retention periods, and your rights regarding your data.
      </p>

      <div>
        <h3 className="font-semibold mb-1">1. Who We Are</h3>
        <ul className="list-disc pl-5 space-y-0.5">
          <li><strong>Controller:</strong> slime design</li>
          <li><strong>Contact:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>Website:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">2. Information We Collect</h3>
        <p>We collect only the minimum information necessary to provide the Service.</p>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-1. Information Collected Automatically</h4>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Anonymous Identifier:</strong> A unique anonymous UID generated by Firebase Anonymous Authentication for each device.</li>
          <li><strong>Subscription Data:</strong> Subscription status and purchase history tied to your Apple ID, managed through RevenueCat.</li>
          <li><strong>AI Usage Counts:</strong> Monthly and lifetime counts of AI feature usage, used to enforce subscription limits and free-trial quotas.</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-2. Information Transmitted During AI Feature Use</h4>
        <p>
          Only after you have <strong>explicitly granted consent</strong> through the in-app consent dialog, the following information is transmitted to the third-party AI processing service <strong>fal.ai (operated by fal - Features &amp; Labels Inc., USA)</strong> for the sole purpose of executing the requested AI operation. Consent is collected on the first invocation of any AI feature and may be revoked at any time from the app&rsquo;s Settings screen.
        </p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">Feature</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Data Sent</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Recipient</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Erase Objects</td>
                <td className="border border-gray-300 px-2 py-1">Captured image + mask image (JPEG/PNG, base64)</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX/LaMa model)</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Replace Background</td>
                <td className="border border-gray-300 px-2 py-1">Captured image + background text prompt</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX.1 Kontext model)</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Style Transfer</td>
                <td className="border border-gray-300 px-2 py-1">Captured image + style instruction prompt</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX.1 Kontext model)</td>
              </tr>
            </tbody>
          </table>
        </div>
        <ul className="list-disc pl-5 space-y-1 mt-2">
          <li><strong>How collected:</strong> The captured image is compressed and resized in-app, with <strong>EXIF metadata (including GPS location and device identifiers) removed</strong>, and transmitted over HTTPS via our Cloud Functions backend to fal.ai.</li>
          <li><strong>Source:</strong> The user&rsquo;s device running the App</li>
          <li><strong>Recipient:</strong> API servers operated by fal - Features &amp; Labels Inc. (California, USA) at <code>fal.ai</code></li>
          <li><strong>Items transmitted:</strong> Only the items in the table above. No name, email, location, IDFA, or other personally identifying information is transmitted.</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-3. Information We Do NOT Collect</h4>
        <p>We expressly do <strong>not</strong> collect the following:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Name, address, phone number, or email address (or any personally identifiable information)</li>
          <li>Location data (GPS or EXIF location metadata)</li>
          <li>Advertising Identifier (IDFA)</li>
          <li>Contacts, calendar, or other personal data</li>
          <li>Biometric data for facial recognition or identification</li>
          <li>Behavioral analytics or tracking data (at initial release)</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">3. How We Use Your Information</h3>
        <p>We use collected information solely for the following purposes:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>To provide the App&rsquo;s features</li>
          <li>To generate the output of AI features</li>
          <li>To manage subscriptions and billing</li>
          <li>To enforce AI usage limits based on your subscription plan or free-trial quota</li>
          <li>To detect and prevent abuse, service interference, and attacks</li>
          <li>To comply with applicable laws</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">4. Sharing of Information</h3>
        <p>We do not share your information with third parties except in the following cases:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>When required by law</li>
          <li>When necessary to protect life, safety, or property</li>
          <li>With sub-processors as described in Section 5</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">5. Sub-Processors</h3>
        <p>The App uses the following third-party services. Your information may be processed by these sub-processors on our behalf:</p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">Provider</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Service</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Data Handled</th>
                <th className="border border-gray-300 px-2 py-1 text-left">Retention</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Apple Inc. (USA)</td>
                <td className="border border-gray-300 px-2 py-1">iOS, App Store, In-App Purchase</td>
                <td className="border border-gray-300 px-2 py-1">Apple ID, purchase data</td>
                <td className="border border-gray-300 px-2 py-1">Per Apple policy</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Google LLC (USA)</td>
                <td className="border border-gray-300 px-2 py-1">Firebase Authentication / Firestore / Cloud Functions / App Check</td>
                <td className="border border-gray-300 px-2 py-1">Anonymous UID, AI usage counts, request logs</td>
                <td className="border border-gray-300 px-2 py-1">Until account deletion</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">fal - Features &amp; Labels Inc. (USA)</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai API (FLUX.1 Kontext / LaMa models)</td>
                <td className="border border-gray-300 px-2 py-1">Captured images, mask images, prompts</td>
                <td className="border border-gray-300 px-2 py-1">Sent with the <code>X-Fal-Store-IO: 0</code> header so input data is <strong>not retained in fal.ai&rsquo;s request history</strong>. Generated images are <strong>auto-deleted from fal.ai&rsquo;s CDN within 1 hour at most</strong>.</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">RevenueCat, Inc. (USA)</td>
                <td className="border border-gray-300 px-2 py-1">Subscription management</td>
                <td className="border border-gray-300 px-2 py-1">Anonymous UID, purchase data</td>
                <td className="border border-gray-300 px-2 py-1">Per RevenueCat policy</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-2">Each sub-processor maintains its own privacy policy, and data is handled in accordance with those policies. The privacy policies of each provider are available below:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Apple Inc.: <a href="https://www.apple.com/legal/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.apple.com/legal/privacy/</a></li>
          <li>Google LLC: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a></li>
          <li>fal - Features &amp; Labels Inc. (fal.ai): <a href="https://fal.ai/legal/privacy-policy" className="text-blue-600 hover:text-blue-800 underline">https://fal.ai/legal/privacy-policy</a></li>
          <li>RevenueCat, Inc.: <a href="https://www.revenuecat.com/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.revenuecat.com/privacy/</a></li>
        </ul>
        <p className="mt-2">We have entered into Data Processing Agreements (DPAs) with each sub-processor, including fal - Features &amp; Labels Inc., and have confirmed that they provide a level of data protection equivalent to or higher than that set forth in this Policy.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">6. International Data Transfer</h3>
        <p>Your data may be transmitted to and stored on servers located outside Japan (primarily in the United States and Europe). The data protection laws of these countries may differ from those of your country of residence. By using the App, you consent to such international transfer.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">7. Data Retention</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Input images, mask images, and prompts sent for AI processing:</strong> We send these requests to fal.ai with the <code>X-Fal-Store-IO: 0</code> header, which instructs fal.ai <strong>not to retain the JSON request payload</strong> in their request-history dashboard.</li>
          <li><strong>AI-generated output image files:</strong> We send the <code>X-Fal-Object-Lifecycle-Preference</code> header to cap the lifetime of generated images on fal.ai&rsquo;s CDN at <strong>1 hour maximum</strong> (auto-deleted thereafter). Our Cloud Functions backend downloads the result image immediately on success and returns it to the user&rsquo;s device; we do not persist it on our side either.</li>
          <li><strong>Anonymous UID and usage counts:</strong> Retained in our Firestore database for subscription management as long as you use the App</li>
          <li><strong>Subscription data:</strong> Retained by RevenueCat as purchase history</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">8. Your Rights</h3>
        <p>You have the following rights regarding your information:</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>Right of Access</strong> — to request disclosure of your information</li>
          <li><strong>Right to Rectification</strong> — to correct inaccurate information</li>
          <li><strong>Right to Erasure</strong> — to request deletion (note: since the UID is device-dependent, uninstalling the App effectively deletes your anonymous record)</li>
          <li><strong>Right to Object</strong> — to restrict certain processing</li>
        </ol>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">GDPR Rights (EU/UK Residents)</h4>
        <p>In addition to the above, if you are a resident of the European Union or United Kingdom, you have:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Right to data portability</li>
          <li>Right to lodge a complaint with a supervisory authority</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">CCPA Rights (California Residents)</h4>
        <p>If you are a California resident, you have:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Right to know what personal information we collect and how we use it</li>
          <li>Right to delete your personal information</li>
          <li>Right to opt-out of sale (note: <strong>we do not sell personal information</strong>)</li>
          <li>Right to non-discrimination for exercising your rights</li>
        </ul>

        <p className="mt-2">To exercise any of these rights, contact <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a>. We will respond within 30 days.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">9. Cookies and Similar Technologies</h3>
        <p>The App does not use web browser cookies. Firebase and RevenueCat SDKs may store anonymous identifiers in local device storage (AsyncStorage), but these are not used for tracking purposes.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">10. Children&rsquo;s Privacy</h3>
        <p>The App is not intended for children under the age of 13. Children under 13 should not use the App without parental consent. If we discover that we have collected information from a child under 13, we will promptly delete such information.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">11. Security</h3>
        <p>We take the following measures to protect your information from unauthorized access, alteration, and disclosure:</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Firebase App Check to prevent unauthorized API access</li>
          <li>HTTPS/TLS encryption for all data transmission</li>
          <li>Server-side subscription verification to prevent client-side tampering</li>
          <li>Data Processing Agreements with all third-party sub-processors</li>
        </ul>
        <p className="mt-1">However, no method of transmission over the internet is 100% secure.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">12. Changes to This Policy</h3>
        <p>We may update this Policy from time to time in response to changes in law, service features, or other circumstances. Updated policies take effect upon posting at <a href="https://yaneyuka.com/epoch-camera-privacy-policy/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/epoch-camera-privacy-policy/</a>.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">13. Governing Law and Jurisdiction</h3>
        <p>This Policy is governed by the laws of Japan. Any disputes arising from this Policy shall be subject to the exclusive jurisdiction of the Tokyo District Court as the court of first instance.</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">14. Contact Us</h3>
        <p>For inquiries regarding this Policy, to request disclosure, or to exercise your rights, please contact:</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>Company:</strong> slime design</li>
          <li><strong>Email:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>Website:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 slime design. All rights reserved.
      </p>
    </div>
  );
}

function JapaneseContent() {
  return (
    <div className="bg-white p-4 rounded border border-gray-300 text-[13px] leading-6 text-gray-800 space-y-3">
      <p className="text-[12px] text-gray-500">
        <strong>最終更新日:</strong> 2026年5月3日 &nbsp;|&nbsp;
        <strong>初版制定日:</strong> 2026年4月23日
      </p>
      <p>
        slime design（以下「当方」）は、iOS アプリケーション「Epoch Camera」（以下「本アプリ」）のご利用にあたり、利用者のプライバシーを尊重し、個人情報の保護に努めます。本プライバシーポリシー（以下「本ポリシー」）は、本アプリにおいて取り扱う情報の種類、収集方法、利用目的、第三者提供先、保管期間、利用者の権利について定めるものです。
      </p>

      <div>
        <h3 className="font-semibold mb-1">1. 事業者情報</h3>
        <ul className="list-disc pl-5 space-y-0.5">
          <li><strong>事業者名:</strong> slime design</li>
          <li><strong>連絡先:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>ウェブサイト:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">2. 収集する情報</h3>
        <p>本アプリは、以下の情報を必要最小限の範囲で収集・処理します。</p>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-1. 自動的に収集される情報</h4>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>匿名識別子:</strong> Firebase Anonymous Authentication により生成される匿名 UID（端末ごとに一意）</li>
          <li><strong>サブスクリプション情報:</strong> Apple ID に紐づくサブスクリプション状態、購入履歴（RevenueCat を通じて管理）</li>
          <li><strong>AI利用回数:</strong> 有料プランの上限管理および無料トライアル回数管理のための、月別・累積利用カウント</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-2. AI機能利用時に送信される情報</h4>
        <p>
          利用者が AI 機能の利用に明示的に同意した場合に限り、以下の情報が処理のために第三者の AI 処理サービス <strong>fal.ai（運営: fal - Features &amp; Labels Inc.、米国）</strong>へ送信されます。同意は本アプリ初回の AI 機能実行時に表示されるダイアログで取得し、設定画面からいつでも取り消すことができます。
        </p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">機能</th>
                <th className="border border-gray-300 px-2 py-1 text-left">送信されるデータ</th>
                <th className="border border-gray-300 px-2 py-1 text-left">送信先</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Erase Objects（不要物除去）</td>
                <td className="border border-gray-300 px-2 py-1">撮影画像 + マスク画像（JPEG/PNG, base64）</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX/LaMa モデル)</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Replace Background（背景置換）</td>
                <td className="border border-gray-300 px-2 py-1">撮影画像 + 背景指示プロンプト（テキスト）</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX.1 Kontext モデル)</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Style Transfer（スタイル変換）</td>
                <td className="border border-gray-300 px-2 py-1">撮影画像 + スタイル指示プロンプト（テキスト）</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai (FLUX.1 Kontext モデル)</td>
              </tr>
            </tbody>
          </table>
        </div>
        <ul className="list-disc pl-5 space-y-1 mt-2">
          <li><strong>収集方法:</strong> 撮影直後に本アプリ内で画像を圧縮・リサイズし、EXIF 情報（位置情報、撮影端末情報を含む）を除去した上で、HTTPS 経由で当方の Cloud Functions サーバーを介して fal.ai へ送信します。</li>
          <li><strong>送信元:</strong> 利用者の端末上の本アプリ</li>
          <li><strong>送信先:</strong> fal - Features &amp; Labels Inc.（米国カリフォルニア州）が運営する <code>fal.ai</code> の API サーバー</li>
          <li><strong>送信される項目:</strong> 上表の通り。利用者の氏名、メールアドレス、位置情報、IDFA 等は一切送信しません。</li>
        </ul>

        <h4 className="font-semibold mt-2 mb-1 text-[12px]">2-3. 収集しない情報</h4>
        <p>以下の情報は<strong>一切収集いたしません</strong>。</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>実名、住所、電話番号、メールアドレスなどの個人識別情報</li>
          <li>位置情報（GPS、EXIF 内の位置情報を含む）</li>
          <li>広告識別子（IDFA）</li>
          <li>連絡先、カレンダーなどの個人データ</li>
          <li>顔認識・人物識別のための生体情報</li>
          <li>利用者の行動ログ、アナリティクス（初回リリース時点）</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">3. 利用目的</h3>
        <p>当方は、収集した情報を以下の目的でのみ利用します。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>本アプリの機能を提供するため</li>
          <li>AI 機能の処理結果を生成するため</li>
          <li>サブスクリプションおよび課金を管理するため</li>
          <li>AI利用回数の上限を管理し、課金プランに応じた利用制限を行うため</li>
          <li>不正利用、サービス妨害、攻撃行為等への対処</li>
          <li>法令遵守のため</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">4. 第三者への提供</h3>
        <p>当方は、利用者の情報を本人の同意なく第三者に提供することはありません。ただし、以下の場合は例外とします。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li>法令に基づく開示請求があった場合</li>
          <li>人の生命、身体または財産の保護のために必要がある場合</li>
          <li>本ポリシー第5条に定めるサブプロセッサーへの提供</li>
        </ol>
      </div>

      <div>
        <h3 className="font-semibold mb-1">5. サブプロセッサー</h3>
        <p>本アプリは、以下の第三者サービスを利用します。利用者の情報の一部は、当該サービスの提供事業者に処理委託されます。</p>
        <div className="overflow-x-auto mt-2">
          <table className="w-full border-collapse text-[12px]">
            <thead>
              <tr className="bg-gray-100">
                <th className="border border-gray-300 px-2 py-1 text-left">事業者</th>
                <th className="border border-gray-300 px-2 py-1 text-left">サービス</th>
                <th className="border border-gray-300 px-2 py-1 text-left">取り扱うデータ</th>
                <th className="border border-gray-300 px-2 py-1 text-left">保存期間</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Apple Inc.（米国）</td>
                <td className="border border-gray-300 px-2 py-1">iOS, App Store, In-App Purchase</td>
                <td className="border border-gray-300 px-2 py-1">Apple ID, 購入情報</td>
                <td className="border border-gray-300 px-2 py-1">Apple ポリシーに準拠</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">Google LLC（米国）</td>
                <td className="border border-gray-300 px-2 py-1">Firebase Authentication / Firestore / Cloud Functions / App Check</td>
                <td className="border border-gray-300 px-2 py-1">匿名UID, AI利用回数, リクエストログ</td>
                <td className="border border-gray-300 px-2 py-1">当方のアカウント削除まで</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">fal - Features &amp; Labels Inc.（米国）</td>
                <td className="border border-gray-300 px-2 py-1">fal.ai API（FLUX.1 Kontext / LaMa モデル）</td>
                <td className="border border-gray-300 px-2 py-1">撮影画像、マスク画像、プロンプト</td>
                <td className="border border-gray-300 px-2 py-1">入力データは <code>X-Fal-Store-IO: 0</code> ヘッダ付きで送信し<strong>リクエスト履歴には保存されません</strong>。生成画像は <strong>fal.ai の CDN 上で最大1時間以内に自動削除</strong>。</td>
              </tr>
              <tr>
                <td className="border border-gray-300 px-2 py-1">RevenueCat, Inc.（米国）</td>
                <td className="border border-gray-300 px-2 py-1">サブスクリプション管理</td>
                <td className="border border-gray-300 px-2 py-1">匿名UID, 購入情報</td>
                <td className="border border-gray-300 px-2 py-1">RevenueCat ポリシーに準拠</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-2">各サブプロセッサーは、それぞれ独自のプライバシーポリシーを有しており、当該ポリシーに従ってデータを取り扱います。各社のプライバシーポリシーは下記からご確認いただけます。</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li>Apple Inc.: <a href="https://www.apple.com/legal/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.apple.com/legal/privacy/</a></li>
          <li>Google LLC: <a href="https://policies.google.com/privacy" className="text-blue-600 hover:text-blue-800 underline">https://policies.google.com/privacy</a></li>
          <li>fal - Features &amp; Labels Inc. (fal.ai): <a href="https://fal.ai/legal/privacy-policy" className="text-blue-600 hover:text-blue-800 underline">https://fal.ai/legal/privacy-policy</a></li>
          <li>RevenueCat, Inc.: <a href="https://www.revenuecat.com/privacy/" className="text-blue-600 hover:text-blue-800 underline">https://www.revenuecat.com/privacy/</a></li>
        </ul>
        <p className="mt-2">当方は、fal - Features &amp; Labels Inc. を含む各サブプロセッサーとの間で Data Processing Agreement（DPA）を締結し、当方が本ポリシーで提供する水準と同等以上のデータ保護措置が講じられていることを確認しています。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">6. 国際データ移転</h3>
        <p>本アプリを提供するにあたり、利用者のデータは日本国外（主に米国および欧州）のサーバーに送信・保管される場合があります。これらの国の個人情報保護規制は、利用者の居住国と異なる場合があります。本アプリの利用により、利用者は当該国へのデータ移転に同意したものとみなされます。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">7. 保存期間</h3>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>AI処理用の入力画像・マスク画像・プロンプト:</strong> 当方は fal.ai への送信時に <code>X-Fal-Store-IO: 0</code> ヘッダを付与しており、fal.ai 側のリクエスト履歴（JSON ペイロード）には<strong>保存されません</strong>。</li>
          <li><strong>AI処理結果（生成済み画像ファイル）:</strong> 当方は <code>X-Fal-Object-Lifecycle-Preference</code> ヘッダにより fal.ai の CDN 上での保存期間を<strong>最大1時間に制限</strong>しています（期限到来後は自動削除）。なお当方の Cloud Functions サーバーは生成画像を即座にダウンロードして利用者の端末へ返却し、それ以降は当方側でも保持しません。</li>
          <li><strong>匿名UID および 利用回数データ:</strong> 当方が管理する Firestore 内に、サブスクリプション管理のため継続的に保存</li>
          <li><strong>サブスクリプション情報:</strong> RevenueCat 側で購入履歴として保管</li>
        </ul>
      </div>

      <div>
        <h3 className="font-semibold mb-1">8. ユーザーの権利</h3>
        <p>利用者は、本アプリで処理される自己の情報について、以下の権利を有します。</p>
        <ol className="list-decimal pl-5 space-y-1 mt-1">
          <li><strong>アクセス権:</strong> 当方が保有する利用者の情報の開示を求める権利</li>
          <li><strong>訂正権:</strong> 不正確な情報の訂正を求める権利</li>
          <li><strong>削除権:</strong> 情報の削除を求める権利（ただし、匿名UIDはデバイス依存のため、アプリのアンインストールにより実質的に削除されます）</li>
          <li><strong>処理停止権:</strong> 特定の処理の停止を求める権利</li>
        </ol>
        <p className="mt-1">これらの権利を行使する場合は、<a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a> までご連絡ください。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">9. Cookie および類似技術</h3>
        <p>本アプリは、Web ブラウザで使用される Cookie を利用しません。Firebase および RevenueCat の SDK が、アプリ内で匿名識別子を AsyncStorage（端末ローカル）に保存する場合がありますが、これらは追跡目的では使用されません。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">10. 子どもの利用</h3>
        <p>本アプリは13歳未満の児童を対象としていません。13歳未満のお子様は、保護者の同意なしに本アプリを利用しないでください。万一、13歳未満の児童から情報を収集したことが判明した場合、当方は速やかに当該情報を削除いたします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">11. セキュリティ</h3>
        <p>当方は、収集した情報を不正アクセス、改ざん、漏洩から保護するため、以下の措置を講じます。</p>
        <ul className="list-disc pl-5 space-y-1 mt-1">
          <li>Firebase App Check による不正なAPIアクセスの防止</li>
          <li>HTTPS/TLS による通信の暗号化</li>
          <li>サーバーサイドでのサブスクリプション検証（クライアント改変による課金回避の防止）</li>
          <li>第三者サービスとの Data Processing Agreement 締結</li>
        </ul>
        <p className="mt-1">ただし、インターネット経由のデータ送信において100%安全な手段は存在しないことをご承知おきください。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">12. ポリシーの変更</h3>
        <p>当方は、法令の変更、サービス内容の変更その他の事情に応じて、本ポリシーを随時変更することがあります。変更後のポリシーは、<a href="https://yaneyuka.com/epoch-camera-privacy-policy/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/epoch-camera-privacy-policy/</a> に掲載した時点から効力を生じます。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">13. 準拠法および管轄</h3>
        <p>本ポリシーは日本法に準拠します。本ポリシーに関連する紛争については、東京地方裁判所を第一審の専属的合意管轄裁判所とします。</p>
      </div>

      <div>
        <h3 className="font-semibold mb-1">14. お問い合わせ</h3>
        <p>本ポリシーに関するご質問、情報開示請求、削除請求等は、下記までご連絡ください。</p>
        <ul className="list-disc pl-5 space-y-0.5 mt-1">
          <li><strong>事業者:</strong> slime design</li>
          <li><strong>メール:</strong> <a href="mailto:info@yaneyuka.com" className="text-blue-600 hover:text-blue-800 underline">info@yaneyuka.com</a></li>
          <li><strong>ウェブサイト:</strong> <a href="https://yaneyuka.com/" className="text-blue-600 hover:text-blue-800 underline">https://yaneyuka.com/</a></li>
        </ul>
      </div>

      <p className="text-[11px] text-gray-500 pt-2 border-t border-gray-200 mt-4">
        © 2026 slime design. All rights reserved.
      </p>
    </div>
  );
}
